routes/web.php
<?php

use App\Http\Controllers\BookshelfController;
use App\Http\Controllers\CommonControl;
use App\Http\Controllers\BookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CommonControl::class, 'index']);
Route::get('/about', [CommonControl::class, 'about']);
Route::resource('books', BookController::class);
Route::resource('bookshelfs', BookshelfController::class);

resources/views/layout/booklayout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>@yield("title") | PrivateLibrary</title>
</head>

<body>
    @include('layout.navigation')
    <div class="container my-5 p-5">
        <h1>@yield('pagetitle')</h1>
        @yield('main_content')
    </div>

</body>

</html>

resources/views/layout/bookshelflayout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>@yield("title") | PrivateLibrary</title>
</head>

<body>
    @include('layout.navigation')
    <div class="container my-5 p-5">
        <h1>@yield('pagetitle')</h1>
        @yield('main_content')
    </div>

</body>

</html>

resources/views/layout/commonlayout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>@yield("title") | PrivateLibrary</title>
</head>

<body>
    @include('layout.navigation')
    <div class="container my-5 p-5">
        <h1 class="mb-4">@yield('pagetitle')</h1>
        @yield('main_content')
    </div>

</body>

</html>

resources/views/layout/navigation.blade.php
<nav class="navbar navbar-expand-sm fixed-top">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="mynavbar">
            <a class="navbar-brand" href="/">PrivateLibra.ry</a>
            <ul class="nav nav-pills">
                <li class="nav-item"><a class="nav-link {{($title == 'HOME')?'active':''}}" href="/">HOME</a></li>
                <li class="nav-item"><a class="nav-link {{($title == 'BOOK')?'active':''}}" href="{{route('books.index')}}">Book</a></li>
                <li class="nav-item"><a class="nav-link {{($title == 'BOOKSHELF')?'active':''}}" href="{{route('bookshelfs.index')}}">Rack Book</a></li>
                <li class="nav-item"><a class="nav-link {{($title == 'ABOUT')?'active':''}}" href="/about">About</a></li>
            </ul>
        </div>
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" id="darkmode">
            <label class="form-check-label" for="darkmode">Dark Mode</label>
        </div>
    </div>
</nav>
<nav class="navbar navbar-expand-sm fixed-bottom justify-content-center mt-5">
    <a class="navbar-brand">Created by SPR @ 2021</a>
</nav>
<script>
    var darkSwitch = document.getElementById("darkmode");

    $(document).ready(function() {
        if (localStorage.getItem("darkmode") === "true") {
            darkmode();
        } else {
            lightmode();
        }
    });
    $(document).ready(function() {
        $("#darkmode").on("click", () => {
            if (darkSwitch.checked) {
                darkmode();
                localStorage.setItem("darkmode", "true");
            } else {
                lightmode();
                localStorage.removeItem("darkmode");
            }
        });
        // $("#submit").on("click", () => {
        //     $("#submit").attr('disabled', true).html("<span class='spinner-border spinner-border-sm'></span> Loading...");
        //     setTimeout(function() {
        //         $("#submit").attr('disabled', false).text("Add New Data");
        //     }, 2000);
        // });
    });

    function darkmode() {
        $("body").addClass("bg-dark text-white");
        $("#table").addClass("table-dark");
        $("#tableshow").addClass("table-dark").removeClass("table-light");
        $(".btn-info").addClass("btn-outline-info").removeClass("btn-info");
        $("#rec").removeClass("carousel-dark");
        $(".btn-warning").addClass("btn-outline-warning").removeClass("btn-warning");
        $(".btn-danger").addClass("btn-outline-danger").removeClass("btn-danger");
        $(".btn-success").addClass("btn-outline-success").removeClass("btn-success");
        $(".card-header").addClass("bg-dark").removeClass("bg-light");
        $(".card-body").addClass("bg-secondary");
        $(".modal-header").addClass("bg-secondary");
        $(".modal-body").addClass("bg-dark");
        $(".modal-footer").addClass("bg-dark");
        $(".card-footer").addClass("bg-dark").removeClass("bg-light");
        $("nav").addClass("navbar-dark bg-dark").removeClass("navbar-light bg-light");
        $("label[for='darkmode']").text("Dark Mode").addClass("text-white");
        $("#darkmode").attr('checked', true);
    }

    function lightmode() {
        $(".btn-outline-info").addClass("btn-info").removeClass("btn-outline-info");
        $(".btn-outline-warning").addClass("btn-warning").removeClass("btn-outline-warning");
        $(".btn-outline-danger").addClass("btn-danger").removeClass("btn-outline-danger");
        $(".btn-outline-success").addClass("btn-success").removeClass("btn-outline-success");
        $(".card-header").addClass("bg-light").removeClass("bg-dark");
        $(".card-body").removeClass("bg-secondary");
        $("#rec").addClass("carousel-dark");
        $(".card-footer").addClass("bg-light").removeClass("bg-dark");
        $(".modal-header").removeClass("bg-secondary");
        $(".modal-body").removeClass("bg-dark");
        $(".modal-footer").removeClass("bg-dark");
        $("nav").addClass("navbar-light bg-light").removeClass("navbar-dark bg-dark");
        $("body").removeClass("bg-dark text-white");
        $("#table").removeClass("table-dark");
        $("#tableshow").addClass("table-light").removeClass("table-dark");
        $("label[for='darkmode']").text("Light Mode").removeClass("text-white");
        $("#darkmode").attr('checked', false);
    }
</script>