routes/web.php
<?php

use App\Http\Controllers\BookshelfController;
use App\Http\Controllers\CommonControl;
use App\Http\Controllers\BookController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [CommonControl::class, 'index']);
Route::get('/about', [CommonControl::class, 'about']);
Route::resource('books', BookController::class);
Route::resource('bookshelfs', BookshelfController::class);

resources/views/viewdata/about.blade.php
@extends('layout.booklayout')
@section('title', 'About')
@section('pagetitle', 'About')
@section ('main_content')
<div class="p-3 bg-secondary text-white rounded">
    <P class="m-3">
    Welcome to PrivateLibra.ry</p>
    <p class="m-3">This project is a open-source, so you can check it on <a class="btn btn-info btn-sm" href="https://github.com/MYSTELTAiNNOfficial/Perpustakaan">GitHub</a></P>
</div>
@endsection

resources/views/viewdata/bookadd.blade.php
@extends('layout.booklayout')
@section('title', 'Add Book')
@section('pagetitle', 'Add New Book')
@section ('main_content')
<form action="{{route('books.store')}}" method="post">
    @csrf
    <div class="mt-4">
        <div class="row">
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="bname" placeholder="Enter Book Name" name="bname">
                    <label for="bname" class="text-dark">Book Name</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="yrbook" placeholder="Enter Year Book Released" name="yrbook">
                    <label for="yrbook" class="text-dark">Year Release</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <select class="form-select" id="type" name="type">
                        @foreach ($bookshelfs as $bkshlf){
                        <option value="{{$bkshlf['code']}}">{{$bkshlf['type_name']}}</option>
                        }
                        @endforeach
                    </select>
                    <label for="type" class="text-dark">Type/Genre</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="author" placeholder="Enter Author Name" name="author">
                    <label for="author" class="text-dark">Author Name</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="publish" placeholder="Enter Publisher Name" name="publish">
                    <label for="publish" class="text-dark">Publisher Name</label>
                </div>
            </div>
        </div>
        <div class="form-floating mb-3 mt-3">
            <input type="text" class="form-control" id="desc" placeholder="Enter Description" name="desc">
            <label for="desc" class="text-dark">Description</label>
        </div>
        <button id="submit" type="submit" class="btn btn-info">
            Add New Data
        </button>
    </div>
</form>
@endsection

resources/views/viewdata/bookedit.blade.php
@extends('layout.booklayout')
@section('title', 'Edit Book')
@section('pagetitle', "Edit ".$book['book_name'])
@section ('main_content')
<form action="{{route('books.update', $book->id)}}" method="post">
    @csrf
    <input type="hidden" name="_method" value="PATCH">
    <div class="mt-4">
        <div class="row">
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="bname" placeholder="Enter Book Name" name="bname" value="{{$book['book_name']}}">
                    <label for="bname" class="text-dark">Book Name</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="yrbook" placeholder="Enter Year Book Released" name="yrbook" value="{{$book['year_release']}}">
                    <label for="yrbook" class="text-dark">Year Release</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <select class="form-select" id="type" name="type">
                        @foreach ($bookshelfs as $bkshlf){
                        @if ($bkshlf['code'] === $book['type_name'])
                        <option value="{{$bkshlf['code']}}" selected>{{$bkshlf['type_name']}}</option>
                        @else
                        <option value="{{$bkshlf['code']}}">{{$bkshlf['type_name']}}</option>
                        @endif

                        }
                        @endforeach
                    </select>
                    <label for="type" class="text-dark">Type/Genre</label>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="author" placeholder="Enter Author Name" name="author" value="{{$book['author']}}">
                    <label for="author" class="text-dark">Author Name</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="publish" placeholder="Enter Publisher Name" name="publish" value="{{$book['publisher']}}">
                    <label for="publish" class="text-dark">Publisher Name</label>
                </div>
            </div>
        </div>
        <div class="form-floating mb-3 mt-3">
            <input type="text" class="form-control" id="desc" placeholder="Enter Description" name="desc" value="{{$book['description']}}">
            <label for="desc" class="text-dark">Description</label>
        </div>
        <button id="submit" type="submit" class="btn btn-info">
            Edit Book
        </button>
    </div>
</form>
@endsection

resources/views/viewdata/bookindex.blade.php
@extends('layout.booklayout')
@section('title', 'Book')
@section('pagetitle', 'All Book List')
@section ('main_content')
<div class="clearfix">
    <a class="btn btn-success float-end" href="{{route('books.create')}}">ADD</a>
</div>
<table id="table" class="table table-sm table-hover table-borderless mt-4">
    <tr>
        <th>NO</th>
        <th>BOOK NAME</th>
        <th>ID</th>
        <th>BOOK TYPE</th>
        <th>YEAR RELEASE</th>
    </tr>

    @foreach ($books as $book)
    <tr>
        <td>{{$loop->index+1}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('books.show', $book->id)}}">{{$book['book_name']}}</a></td>
        <td>{{$book['id']}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('bookshelfs.show', $book->bookshelf->code)}}">{{$book->bookshelf->type_name}}</a></td>
        <td>{{$book['year_release']}}</td>
    </tr>
    @endforeach
</table>
<div class="mt-10">
{{$books->links()}}
</div>
@endsection

resources/views/viewdata/bookinfo.blade.php
@extends('layout.booklayout')
@section('title', 'Book')
@section('pagetitle', $book['book_name'])
@section ('main_content')
<div class="clearfix mb-3">
    <div class="btn-group float-end">
        <a class="btn btn-warning btn-sm" href="{{route('books.edit', $book->id)}}">UPDATE</a>
        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteConfirm">DELETE</button>
    </div>
</div>
<div class="modal fade" id="deleteConfirm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">Delete {{$book['book_name']}} ({{$book['id']}})
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">Do you want to delete {{$book['book_name']}} from {{$book->bookshelf->type_name}} Bookshelf?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info btn-sm" data-bs-dismiss="modal">No</button>
                <form action="{{route('books.destroy', $book->id)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="p-5 bg-secondary text-white rounded">
    <p>Code: {{$book['id']}}</p>
    <p>Author: {{$book['author']}}</p>
    <p>Publisher: {{$book['publisher']}}</p>
    <p>Year Released: {{$book['year_release']}}</p>
    <p>Description: {{$book['description']}}</p>
</div>
@endsection

resources/views/viewdata/home.blade.php
@extends('layout.commonlayout')
@section('title', 'Home')
@section('pagetitle', 'Welcome to PrivateLibra.ry')
@section ('main_content')
<h4>Here's Our Book Recommendation</h4>
<!-- Start Recommend Section -->
<div id="rec" class="carousel slide mt-4" data-bs-ride="carousel">
    <div class="carousel-indicators">
        @foreach ($randbookrec->chunk(3) as $data)
        @if ($loop->first)
        <button type="button" data-bs-target="#rec" data-bs-slide-to="{{$loop->index}}" class="active"></button>
        @else
        <button type="button" data-bs-target="#rec" data-bs-slide-to="{{$loop->index}}"></button>
        @endif

        @endforeach
    </div>
    <div class="carousel-inner">
        @foreach ($randbookrec->chunk(3) as $data)
        @if ($loop->first)
        <div class="carousel-item active">
            <div class="row">
                @foreach ($data as $book)
                <div class="col">
                    <div class="card">
                        <div class="card-header">{{$book['book_name']}}</div>
                        <div class="card-body">{{$book['description']}}</div>
                        <div class="card-footer"><a class="btn btn-info btn-sm" href="{{route('bookshelfs.show', $book->bookshelf->code)}}">{{$book->bookshelf->type_name}}</a></div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        @else
        <div class="carousel-item">
            <div class="row">
                @foreach ($data as $book)
                <div class="col">
                    <div class="card">
                        <div class="card-header">{{$book['book_name']}}</div>
                        <div class="card-body">{{$book['description']}}</div>
                        <div class="card-footer"><a class="btn btn-info btn-sm" href="{{route('bookshelfs.show', $book->bookshelf->code)}}">{{$book->bookshelf->type_name}}</a></div>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        @endif
        @endforeach
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#rec" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#rec" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
    </button>
</div>

<!-- End Recommend Section -->
<!-- Start New Added Section -->
<h4 class="mt-5">Here's Our New Book</h4>
<div class="row mt-4">
    @foreach ($latest as $book)
    <div class="col">
        <div class="card">
            <div class="card-header">{{$book['book_name']}}</div>
            <div class="card-body">{{$book['description']}}</div>
            <div class="card-footer"><a class="btn btn-info btn-sm" href="{{route('bookshelfs.show', $book->bookshelf->code)}}">{{$book->bookshelf->type_name}}</a></div>
        </div>
    </div>
    @endforeach
</div>
<!-- End New Added Section -->
@endsection

resources/views/viewdata/rackadd.blade.php
@extends('layout.bookshelflayout')
@section('title', 'Add Bookshelf')
@section('pagetitle', 'Add New Type/Genre')
@section ('main_content')
<form action="{{route('bookshelfs.store')}}" method="post">
    @csrf
    <div class="mt-4">
        <div class="row">
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="rcode" placeholder="Rack Code" name="rcode">
                    <label for="rcode" class="text-dark">Rack Code</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="tbname" placeholder="Enter Type Book Name" name="tbname">
                    <label for="tbname" class="text-dark">Type Book Name</label>
                </div>
            </div>
        </div>
        <div class="form-floating mb-3 mt-3">
            <input type="text" class="form-control" id="desc" placeholder="Enter Description" name="desc">
            <label for="desc" class="text-dark">Description</label>
        </div>
        <button id="submit" type="submit" class="btn btn-info">
            Add New Data
        </button>
    </div>
</form>
@endsection

resources/views/viewdata/rackedit.blade.php
@extends('layout.bookshelflayout')
@section('title', 'Edit Bookshelf')
@section('pagetitle', "Edit ".$bookshelf['type_name'])
@section ('main_content')
<form action="{{route('bookshelfs.update', $bookshelf->code)}}" method="post">
    @csrf
    <input type="hidden" name="_method" value="PATCH">
    <div class="mt-4">
        <div class="row">
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="ccode" placeholder="Rack Code" name="rcode" value="{{$bookshelf['code']}}">
                    <label for="ccode" class="text-dark">Rack Code</label>
                </div>
            </div>
            <div class="col">
                <div class="form-floating mb-3 mt-3">
                    <input type="text" class="form-control" id="cname" placeholder="Enter Type Book Name" name="tbname" value="{{$bookshelf['type_name']}}">
                    <label for="cname" class="text-dark">Type Book Name</label>
                </div>
            </div>
        </div>
        <div class="form-floating mb-3 mt-3">
            <input type="text" class="form-control" id="desc" placeholder="Enter Description" name="desc" value="{{$bookshelf['description']}}">
            <label for="desc" class="text-dark">Description</label>
        </div>
        <button id="submit" type="submit" class="btn btn-info">
            Update Data
        </button>
    </div>
</form>
@endsection

resources/views/viewdata/rackindex.blade.php
@extends('layout.bookshelflayout')
@section('title', 'Bookshelf')
@section('pagetitle', 'All Type/Genre Book List')
@section ('main_content')
<div class="clearfix mb-3">
    <a class="btn btn-success float-end" href="{{route('bookshelfs.create')}}">ADD</a>
</div>


@foreach ($bookshelfs->chunk(3) as $chunked)
<div class="row mb-4">
    @foreach ($chunked as $bhlf)
    <div class="col">
        <div class="card">
            <div class="card-header">{{$bhlf['code']}}</div>
            <div class="card-body">{{$bhlf['type_name']}}</div>
            <div class="card-footer">
                <div class="btn-group">
                    <a class="btn btn-info btn-sm" href="{{route('bookshelfs.show', $bhlf->code)}}">DETAIL</a>
                </div>
            </div>
        </div>
    </div>
    @endforeach
</div>
@endforeach
{{$bookshelfs->links()}}
@endsection

resources/views/viewdata/rackinfo.blade.php
@extends('layout.bookshelflayout')
@section('title', 'Bookshelf')
@section('pagetitle', $bookshelf['type_name'])
@section ('main_content')
<div class="clearfix mb-3">
    <div class="btn-group float-end">
        <a class="btn btn-warning btn-sm" href="{{route('bookshelfs.edit', $bookshelf->code)}}">UPDATE</a>
        <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteConfirm">DELETE</button>
    </div>
</div>
<div class="modal fade" id="deleteConfirm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">Delete {{$bookshelf['type_name']}} ({{$bookshelf['code']}})
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">Do you want to delete {{$bookshelf['type_name']}} from Bookshelf?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info btn-sm" data-bs-dismiss="modal">No</button>
                <form action="{{route('bookshelfs.destroy', $bookshelf->code)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-sm">Yes</button>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="mt-4 p-5 bg-secondary text-white rounded">
    <p>Code: {{$bookshelf['code']}}</p>
    <p>Description: {{$bookshelf['description']}}</p>
</div>
<h4 class="mt-5 mb-3">List Book in {{$bookshelf['type_name']}} Bookshelf</h4>
<table id="tableshow" class="table table-hover table-sm table-borderless mt-4">
    <tr>
        <th>NO</th>
        <th>BOOK NAME</th>
        <th>ID</th>
        <th>YEAR RELEASE</th>
    </tr>

    @foreach ($bookshelf->books as $book)
    <tr>
        <td>{{$loop->index+1}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('books.show', $book->id)}}">{{$book['book_name']}}</a></td>
        <td>{{$book['id']}}</a></td>
        <td>{{$book['year_release']}}</td>
    </tr>
    @endforeach
</table>
@endsection